### ISSUE TITLE
Getting Error...

### ISSUE THREAD

**Issue by m-guha** [discdiver/event-driven#47]
Watched your you tube demo...

Was able to successfully create webhook & communicate with Github as well (you tube video till minute 4). However when I try for deployment with  flow.py, I am getting error. Have changed source to point to my Gith hub which has the url of webhook created for my account.

Error - copy -pasted below: 

Traceback (most recent call last):
  File "/home/opc/flow.py", line 11, in <module>
    print_issue.from_source(
  File "/home/opc/.local/lib/python3.9/site-packages/prefect/utilities/asyncutil                                                                                                             s.py", line 259, in coroutine_wrapper
    return call()
  File "/home/opc/.local/lib/python3.9/site-packages/prefect/_internal/concurren                                                                                                             cy/calls.py", line 398, in __call__
    return self.result()
  File "/home/opc/.local/lib/python3.9/site-packages/prefect/_internal/concurren                                                                                                             cy/calls.py", line 284, in result
    return self.future.result(timeout=timeout)
  File "/home/opc/.local/lib/python3.9/site-packages/prefect/_internal/concurren                                                                                                             cy/calls.py", line 168, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_re                                                                                                             sult
    raise self._exception
  File "/home/opc/.local/lib/python3.9/site-packages/prefect/_internal/concurren                                                                                                             cy/calls.py", line 355, in _run_async
    result = await coro
  File "/home/opc/.local/lib/python3.9/site-packages/prefect/flows.py", line 856                                                                                                             , in from_source
    await storage.pull_code()
  File "/home/opc/.local/lib/python3.9/site-packages/prefect/runner/storage.py",                                                                                                              line 233, in pull_code
    await self._clone_repo()
  File "/home/opc/.local/lib/python3.9/site-packages/prefect/runner/storage.py",                                                                                                              line 257, in _clone_repo
    await run_process(cmd)
  File "/usr/local/lib/python3.9/site-packages/anyio/_core/_subprocesses.py", li                                                                                                             ne 62, in run_process
    async with await open_process(
  File "/usr/local/lib/python3.9/site-packages/anyio/_core/_subprocesses.py", li                                                                                                             ne 126, in open_process
    return await get_asynclib().open_process(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", lin                                                                                                             e 1041, in open_process
    process = await asyncio.create_subprocess_exec(
  File "/usr/lib64/python3.9/asyncio/subprocess.py", line 236, in create_subproc                                                                                                             ess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1676, in subprocess_e                                                                                                             xec
    transport = await self._make_subprocess_transport(
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 197, in _make_subproc                                                                                                             ess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib64/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'

Any suggestion or recommendations?

**Comment by discdiver** [comment]
Do you have git installed in the environment where you're working?
